# =============================================================================
# Touchstone Format Export
# =============================================================================
#
# This file provides export to Touchstone format (.sNp files),
# the industry standard for S-parameter data exchange.
#
# Supports:
# - 1-port (.s1p), 2-port (.s2p), N-port (.sNp) formats
# - DB (dB), MA (magnitude-angle), RI (real-imaginary) formats
# - Frequency sweep data
#
# =============================================================================

"""
    _write_sparam_pair(io, s, format)

Write a single S-parameter value pair to io in the specified Touchstone format.
"""
function _write_sparam_pair(io::IO, s::Complex, format::Symbol)
    if format == :db
        db_val = 20 * log10(abs(s))
        ang_deg = rad2deg(angle(s))
        print(io, @sprintf("%.12g %.12g ", db_val, ang_deg))
    elseif format == :ma
        mag = abs(s)
        ang_deg = rad2deg(angle(s))
        print(io, @sprintf("%.12g %.12g ", mag, ang_deg))
    else  # :ri
        print(io, @sprintf("%.12g %.12g ", real(s), imag(s)))
    end
end

"""
    _parse_sparam_pair(v1, v2, format_type)

Parse a single S-parameter value pair from Touchstone data.
"""
function _parse_sparam_pair(v1::FT, v2::FT, format_type::Symbol) where {FT<:Real}
    if format_type == :db
        mag = 10^(v1 / 20)
        ang = deg2rad(v2)
        return mag * cis(ang)
    elseif format_type == :ma
        mag = v1
        ang = deg2rad(v2)
        return mag * cis(ang)
    else  # :ri
        return complex(v1, v2)
    end
end

"""
    saveTouchstone(filename::String, sparams::SParameterResult;
                   format::Symbol=:db,
                   comment::String="")

Save S-parameters in Touchstone format.

Touchstone format is the industry standard for S-parameter data exchange,
supported by all major RF/Microwave CAD tools (ADS, HFSS, CST, etc.).

# File Naming
- 1-port: filename should end in .s1p
- 2-port: filename should end in .s2p
- N-port: filename should end in .sNp (where N is number of ports)

# Formats
- `:db` - dB and angle (e.g., "-10.0 90.0")
- `:ma` - magnitude and angle (e.g., "0.316 90.0")
- `:ri` - real and imaginary (e.g., "0.0 0.316")

# Arguments
- `filename::String`: Output file path
- `sparams::SParameterResult`: S-parameter data
- `format::Symbol`: Export format (:db, :ma, :ri)
- `comment::String`: Optional comment header

# Example
```julia
sparams = computeSParameters(ports, Zmat, nbf)
saveTouchstone("coupler.s2p", sparams; format=:db)
```
"""
function saveTouchstone(
    filename::String,
    sparams::SParameterResult{FT};
    format::Symbol=:db,
    comment::String=""
) where {FT<:Real}
    
    # Validate format
    if !(format in (:db, :ma, :ri))
        error("Invalid format: $format. Use :db, :ma, or :ri")
    end
    
    num_ports = sparams.num_ports
    num_freqs = sparams.num_frequencies
    
    # Open file
    open(filename, "w") do io
        # Header comments
        println(io, "! Touchstone S-parameter file")
        if !isempty(comment)
            for line in split(comment, '\n')
                println(io, "! ", line)
            end
        end
        println(io, "! Generated by Julia_MoM")
        println(io, "! Number of ports: ", num_ports)
        println(io, "! Reference impedance: ", sparams.Z0, " Ohms")
        println(io, "! Number of frequency points: ", num_freqs)
        
        # Option line
        # Format: # <frequency_unit> <parameter> <format> R <reference_impedance>
        format_str = format == :db ? "DB" : format == :ma ? "MA" : "RI"
        println(io, "# Hz S ", format_str, " R ", sparams.Z0)
        
        # Data section
        for f_idx in 1:num_freqs
            freq = sparams.frequencies[f_idx]

            # Frequency value
            print(io, freq, " ")

            pair_count = 0  # Track pairs on current line (max 4 per spec)

            if num_ports == 1
                # 1-port: trivial — one pair on one line
                _write_sparam_pair(io, sparams.S[1, 1, f_idx], format)
                println(io)
            elseif num_ports == 2
                # 2-port: special order S11, S21, S12, S22 (spec Rev 1.1 §2.3)
                for (i, j) in [(1,1), (2,1), (1,2), (2,2)]
                    _write_sparam_pair(io, sparams.S[i, j, f_idx], format)
                end
                println(io)
            else
                # N-port (N >= 3): row-major order, max 4 pairs per line
                for i in 1:num_ports
                    for j in 1:num_ports
                        if pair_count >= 4
                            println(io)
                            print(io, " ")  # Continuation line indented
                            pair_count = 0
                        end
                        _write_sparam_pair(io, sparams.S[i, j, f_idx], format)
                        pair_count += 1
                    end
                    # Each matrix row starts on a new line
                    println(io)
                    pair_count = 0
                end
            end
        end
    end
    
    return filename
end

"""
    saveTouchstone(filename::String, S::Matrix{CT}, freq::Real, Z0::Real=50.0; kwargs...) where CT

Save single-frequency S-parameters in Touchstone format.

Convenience method for saving a single S-matrix without creating SParameterResult.

# Arguments
- `filename::String`: Output file path
- `S::Matrix{Complex}`: S-parameter matrix (N×N)
- `freq::Real`: Frequency in Hz
- `Z0::Real`: Reference impedance
- `kwargs...`: Additional options (format, comment)
"""
function saveTouchstone(
    filename::String,
    S::Matrix{CT},
    freq::FT,
    Z0::FT=FT(50.0);
    kwargs...
) where {CT<:Complex, FT<:Real}
    
    num_ports = size(S, 1)
    portIDs = collect(1:num_ports)
    
    sparams = SParameterResult(
        S, S, [freq], Z0, portIDs
    )
    
    return saveTouchstone(filename, sparams; kwargs...)
end

"""
    loadTouchstone(filename::String)

Load S-parameters from Touchstone format file.

# Arguments
- `filename::String`: Input file path

# Returns
- `SParameterResult`: Loaded S-parameter data

# Example
```julia
sparams = loadTouchstone("coupler.s2p")
S11 = sparams.S[1,1,:]  # S11 across all frequencies
```
"""
function loadTouchstone(filename::String)
    lines = readlines(filename)
    
    # Parse header
    # Spec defaults for bare '#' option line: GHz, S, MA, R 50
    freq_unit = :ghz
    parameter_type = :S
    format_type = :ma
    Z0 = 50.0

    data_lines = String[]

    for line in lines
        line = strip(line)

        # Skip empty lines
        isempty(line) && continue

        # Comment line (starts with !)
        if startswith(line, '!')
            continue
        end

        # Option line
        if startswith(line, '#')
            parts = split(line)
            # Parse: # Hz S DB R 50.0
            for (i, part) in enumerate(parts)
                part_lower = lowercase(part)
                if part_lower in ("hz", "khz", "mhz", "ghz")
                    freq_unit = Symbol(part_lower)
                elseif part in ("S", "Y", "Z", "H", "G")
                    parameter_type = Symbol(part)
                elseif part in ("DB", "MA", "RI")
                    format_type = Symbol(lowercase(part))
                elseif part == "R" && i < length(parts)
                    Z0 = parse(Float64, parts[i+1])
                end
            end
        else
            # Data line — strip inline comments (text after !)
            comment_pos = findfirst("!", line)
            if comment_pos !== nothing
                line = line[1:first(comment_pos)-1]
            end
            push!(data_lines, strip(line))
        end
    end
    
    # Parse data: concatenate all data values into a flat array, then split by frequency
    all_values = Float64[]
    for line in data_lines
        append!(all_values, parse.(Float64, split(line)))
    end

    # Determine number of ports from the first frequency point
    # Each frequency has 1 freq value + 2*N^2 S-parameter values
    # For 1-port: 3 values, 2-port: 9 values, etc.
    # Try to infer from total number of values
    values_per_freq = nothing
    for n in 1:100
        vp = 1 + 2 * n * n
        if length(all_values) % vp == 0
            values_per_freq = vp
            num_ports = n
            break
        end
    end
    if values_per_freq === nothing
        error("Cannot determine number of ports from data")
    end

    num_freqs = length(all_values) ÷ values_per_freq

    FT = Float64
    CT = Complex{FT}

    freqs = Vector{FT}(undef, num_freqs)
    S = Array{CT,3}(undef, num_ports, num_ports, num_freqs)

    for f_idx in 1:num_freqs
        offset = (f_idx - 1) * values_per_freq
        freq_raw = all_values[offset + 1]

        # Convert frequency unit if needed
        if freq_unit == :khz
            freqs[f_idx] = freq_raw * 1e3
        elseif freq_unit == :mhz
            freqs[f_idx] = freq_raw * 1e6
        elseif freq_unit == :ghz
            freqs[f_idx] = freq_raw * 1e9
        else
            freqs[f_idx] = freq_raw
        end

        # Parse S-parameters
        val_idx = offset + 2
        if num_ports == 2
            # 2-port: spec order is S11, S21, S12, S22
            for (i, j) in [(1,1), (2,1), (1,2), (2,2)]
                v1 = all_values[val_idx]
                v2 = all_values[val_idx + 1]
                S[i,j,f_idx] = _parse_sparam_pair(v1, v2, format_type)
                val_idx += 2
            end
        else
            # N-port (N >= 3): row-major order
            for i in 1:num_ports, j in 1:num_ports
                v1 = all_values[val_idx]
                v2 = all_values[val_idx + 1]
                S[i,j,f_idx] = _parse_sparam_pair(v1, v2, format_type)
                val_idx += 2
            end
        end
    end
    
    portIDs = collect(1:num_ports)
    
    return SParameterResult(S, S, freqs, FT(Z0), portIDs)
end

# =============================================================================
# Exports
# =============================================================================

export saveTouchstone, loadTouchstone
