# =============================================================================
# Touchstone Format Export
# =============================================================================
#
# This file provides export to Touchstone format (.sNp files),
# the industry standard for S-parameter data exchange.
#
# Supports:
# - 1-port (.s1p), 2-port (.s2p), N-port (.sNp) formats
# - DB (dB), MA (magnitude-angle), RI (real-imaginary) formats
# - Frequency sweep data
#
# =============================================================================

"""
    saveTouchstone(filename::String, sparams::SParameterResult; 
                   format::Symbol=:db,
                   comment::String="")

Save S-parameters in Touchstone format.

Touchstone format is the industry standard for S-parameter data exchange,
supported by all major RF/Microwave CAD tools (ADS, HFSS, CST, etc.).

# File Naming
- 1-port: filename should end in .s1p
- 2-port: filename should end in .s2p
- N-port: filename should end in .sNp (where N is number of ports)

# Formats
- `:db` - dB and angle (e.g., "-10.0 90.0")
- `:ma` - magnitude and angle (e.g., "0.316 90.0")
- `:ri` - real and imaginary (e.g., "0.0 0.316")

# Arguments
- `filename::String`: Output file path
- `sparams::SParameterResult`: S-parameter data
- `format::Symbol`: Export format (:db, :ma, :ri)
- `comment::String`: Optional comment header

# Example
```julia
sparams = computeSParameters(ports, Zmat, nbf)
saveTouchstone("coupler.s2p", sparams; format=:db)
```
"""
function saveTouchstone(
    filename::String,
    sparams::SParameterResult{FT};
    format::Symbol=:db,
    comment::String=""
) where {FT<:Real}
    
    # Validate format
    if !(format in (:db, :ma, :ri))
        error("Invalid format: $format. Use :db, :ma, or :ri")
    end
    
    num_ports = sparams.num_ports
    num_freqs = sparams.num_frequencies
    
    # Open file
    open(filename, "w") do io
        # Header comments
        println(io, "! Touchstone S-parameter file")
        if !isempty(comment)
            for line in split(comment, '\n')
                println(io, "! ", line)
            end
        end
        println(io, "! Generated by Julia_MoM")
        println(io, "! Number of ports: ", num_ports)
        println(io, "! Reference impedance: ", sparams.Z0, " Ohms")
        println(io, "! Number of frequency points: ", num_freqs)
        
        # Option line
        # Format: # <frequency_unit> <parameter> <format> R <reference_impedance>
        format_str = format == :db ? "DB" : format == :ma ? "MA" : "RI"
        println(io, "# Hz S ", format_str, " R ", sparams.Z0)
        
        # Data section
        for f_idx in 1:num_freqs
            freq = sparams.frequencies[f_idx]
            
            # Frequency value
            print(io, freq, " ")
            
            # S-parameters for all port combinations
            # Order: S11, S21, S12, S22 for 2-port (column-major in matrix)
            # Actually Touchstone expects: S11, S21, S12, S22 (row by row)
            for j in 1:num_ports, i in 1:num_ports
                s = sparams.S[i, j, f_idx]
                
                if format == :db
                    # dB and angle (degrees)
                    db_val = 20 * log10(abs(s))
                    ang_deg = rad2deg(angle(s))
                    print(io, @sprintf("%.12g %.12g ", db_val, ang_deg))
                    
                elseif format == :ma
                    # Magnitude and angle (degrees)
                    mag = abs(s)
                    ang_deg = rad2deg(angle(s))
                    print(io, @sprintf("%.12g %.12g ", mag, ang_deg))
                    
                else  # :ri
                    # Real and imaginary
                    print(io, @sprintf("%.12g %.12g ", real(s), imag(s)))
                end
            end
            
            println(io)  # New line after each frequency
        end
    end
    
    return filename
end

"""
    saveTouchstone(filename::String, S::Matrix{CT}, freq::Real, Z0::Real=50.0; kwargs...) where CT

Save single-frequency S-parameters in Touchstone format.

Convenience method for saving a single S-matrix without creating SParameterResult.

# Arguments
- `filename::String`: Output file path
- `S::Matrix{Complex}`: S-parameter matrix (N×N)
- `freq::Real`: Frequency in Hz
- `Z0::Real`: Reference impedance
- `kwargs...`: Additional options (format, comment)
"""
function saveTouchstone(
    filename::String,
    S::Matrix{CT},
    freq::FT,
    Z0::FT=FT(50.0);
    kwargs...
) where {CT<:Complex, FT<:Real}
    
    num_ports = size(S, 1)
    portIDs = collect(1:num_ports)
    
    sparams = SParameterResult(
        S, S, [freq], Z0, portIDs
    )
    
    return saveTouchstone(filename, sparams; kwargs...)
end

"""
    loadTouchstone(filename::String)

Load S-parameters from Touchstone format file.

# Arguments
- `filename::String`: Input file path

# Returns
- `SParameterResult`: Loaded S-parameter data

# Example
```julia
sparams = loadTouchstone("coupler.s2p")
S11 = sparams.S[1,1,:]  # S11 across all frequencies
```
"""
function loadTouchstone(filename::String)
    lines = readlines(filename)
    
    # Parse header
    freq_unit = :Hz
    parameter_type = :S
    format_type = :db
    Z0 = 50.0
    
    data_lines = String[]
    
    for line in lines
        line = strip(line)
        
        # Skip empty lines
        isempty(line) && continue
        
        # Comment line
        if startswith(line, '!')
            continue
        end
        
        # Option line
        if startswith(line, '#')
            parts = split(line)
            # Parse: # Hz S DB R 50.0
            for (i, part) in enumerate(parts)
                if part in ("Hz", "KHz", "MHz", "GHz", "THz", "PHz")
                    freq_unit = Symbol(part)
                elseif part in ("S", "Y", "Z", "H", "G")
                    parameter_type = Symbol(part)
                elseif part in ("DB", "MA", "RI")
                    format_type = Symbol(lowercase(part))
                elseif part == "R" && i < length(parts)
                    Z0 = parse(Float64, parts[i+1])
                end
            end
        else
            # Data line
            push!(data_lines, line)
        end
    end
    
    # Parse data
    num_data_cols = length(split(data_lines[1]))
    num_freqs = length(data_lines)
    
    # Determine number of ports from data columns
    # Format: freq S11 S11(ang) S21 S21(ang) ... for 2-port
    # Each S-parameter takes 2 columns
    num_ports = Int(sqrt((num_data_cols - 1) / 2))
    
    FT = Float64
    CT = Complex{FT}
    
    freqs = Vector{FT}(undef, num_freqs)
    S = Array{CT,3}(undef, num_ports, num_ports, num_freqs)
    
    for (line_idx, line) in enumerate(data_lines)
        values = parse.(FT, split(line))
        freqs[line_idx] = values[1]
        
        # Convert frequency unit if needed
        if freq_unit == :KHz
            freqs[line_idx] *= 1e3
        elseif freq_unit == :MHz
            freqs[line_idx] *= 1e6
        elseif freq_unit == :GHz
            freqs[line_idx] *= 1e9
        elseif freq_unit == :THz
            freqs[line_idx] *= 1e12
        end
        
        # Parse S-parameters
        val_idx = 2
        for j in 1:num_ports, i in 1:num_ports
            v1 = values[val_idx]
            v2 = values[val_idx + 1]
            
            if format_type == :db
                mag = 10^(v1 / 20)
                ang = deg2rad(v2)
                S[i,j,line_idx] = mag * cis(ang)
            elseif format_type == :ma
                mag = v1
                ang = deg2rad(v2)
                S[i,j,line_idx] = mag * cis(ang)
            else  # :ri
                S[i,j,line_idx] = complex(v1, v2)
            end
            
            val_idx += 2
        end
    end
    
    portIDs = collect(1:num_ports)
    
    return SParameterResult(S, S, freqs, FT(Z0), portIDs)
end

# =============================================================================
# Exports
# =============================================================================

export saveTouchstone, loadTouchstone
